# Generated by Django 3.2 on 2021-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('street_number', models.CharField(max_length=16)),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('area', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('latitude', models.DecimalField(max_digits=10, decimal_places=7)),
                ('longitude', models.DecimalField(max_digits=10, decimal_places=7)),
                ('description', models.TextField())
            ],
        ),
    ]
