# Generated by Django 3.2.13 on 2022-05-02 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='api.building'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('city', 'street', 'street_number')},
        ),
    ]
