# Generated by Django 3.2.13 on 2022-05-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_copy_building_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='street_number',
        ),
    ]
